# Generated by Django 5.1.6 on 2025-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, default="user", max_length=5, null=True, verbose_name="Роль"),
        ),
    ]
