version: "3.11.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulletin_board
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db_bulletin_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: redis_bulletin_board
    image: redis:7.4
    restart: always
    ports:
      - "6380:6379"
    env_file: "./.env"
    volumes:
      - ./redis/data:/root/redis

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_bulletin_board
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: