# Generated by Django 5.1.6 on 2025-03-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Название товара")),
                ("price", models.PositiveIntegerField(blank=True, null=True, verbose_name="Цена")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True, verbose_name="Описание товара"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата публикации")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_advertisement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "db_table": "advertisements",
            },
        ),
    ]
