# Generated by Django 5.1.6 on 2025-03-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0004_advertisement_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="role",
        ),
    ]
